### ISSUE TITLE
A way not to hard-code many upstream version numbers in Dockerfile

### ISSUE THREAD

**Issue by dreamcat4** [glerchundi/container-s6-overlay-builder#5]
In our `Dockerfile`, we have version numbers har-coded, in the ADD urls, e.g.

https://github.com/glerchundi/container-s6-overlay-builder/blob/master/Dockerfile#L20

Where the version of `fix-attrs` package is different than `execline` package. And `s6` package is yet a different version too.

It would be neater if we could set each seperate versions of each upstream source packages in some central `manifest.txt` file. Or to be downloaded from a `.txt` webpage on upstream `s6-builder` repo. 

ATM the latest version numbers of each ones are hard-coded into our local Dockerfile.

If we can't use ENV to set them. Then maybe we could instead generate Dockerfile dynamically from a script (simple string substitution). To set the right version numbers.

It's not *super important*. If 'no' then fine. No big deal. Just a suggestion.

**Comment by glerchundi** [comment]
it's not important but easy to do and will help automating everything. it's done.

thanks!
